// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqobulupoaukigohfoun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxb2J1bHVwb2F1a2lnb2hmb3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODE5OTEsImV4cCI6MjA3MTI1Nzk5MX0.hah5lakk8KvqOprgbCwDZgfSSzwteOGhZJqS1JFAfZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});